### ISSUE TITLE
Commands don't work with version 3, which is the default.

### ISSUE THREAD

**Issue by mrobbert** [huit/puppet-gitolite#4]
The commands for install and setup appear to be for Gitolite v2, but the default manifest installs v3 which uses completely different  commands. I think that the commands should be upgraded to use the new version. I can probably help, but I'll warn  you that I am just getting started with gitolite so I'm learning at the same time.

**Comment by hakamadare** [comment]
Heh, I am _by no means_ a gitolite expert :)  Please send a pull request and we'll see how it works!

**Comment by mrobbert** [comment]
I'm not a gitolite expert either which is why I was hoping this Puppet module would help ease the pain of installation. I don't have a patch to submit at this time, I was hoping that there was some explanation behind the decision to install v3, without using v3 commands. Is this code not expected to work out of the box?

**Comment by hakamadare** [comment]
The explanation is that I took a quick look at gitolite, said "oh hey, there's a new release", and bumped the default version number.  This code is v0.0.2; I would certainly like for it to work out of the box, but I am not yet willing to guarantee a painless turnkey install. :)  In brief: thanks for your report, I'll take a look at it as soon as I can.
